const { getStyles } = require('./styles');

function buildEmailTemplate(phProducts, hnStories) {
  const today = new Date().toLocaleDateString('en-US', {
    month: 'long',
    day: 'numeric',
    year: 'numeric'
  });

  const phSection = phProducts.length > 0
    ? buildProductHuntSection(phProducts)
    : '<p style="color: #999; font-style: italic;">Product Hunt data unavailable today</p>';

  const hnSection = hnStories.length > 0
    ? buildHackerNewsSection(hnStories)
    : '<p style="color: #999; font-style: italic;">Hacker News data unavailable today</p>';

  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Your Daily Digest - ${today}</title>
      ${getStyles()}
    </head>
    <body>
      <div class="container">
        <h1>Your Daily Digest</h1>
        <p style="color: #666; font-size: 14px;">${today}</p>

        <div class="section">
          <h2>🚀 Product Hunt</h2>
          ${phSection}
        </div>

        <div class="section">
          <h2>📰 Hacker News</h2>
          ${hnSection}
        </div>

        <div class="footer">
          Generated by OpenPaw Daily Digest
        </div>
      </div>
    </body>
    </html>
  `;
}

function buildProductHuntSection(products) {
  return products.map(product => {
    const videoEmbed = product.videoUrl
      ? `<div class="video-container">
           <video controls width="100%" style="max-height: 300px;">
             <source src="${product.videoUrl}" type="video/mp4">
             Your email client doesn't support video.
           </video>
         </div>`
      : '';

    return `
      <div class="item">
        <div class="item-title">
          <a href="${product.url}">${product.name}</a>
        </div>
        <div class="item-tagline">${product.tagline}</div>
        ${videoEmbed}
        <div class="item-meta">
          👍 ${product.upvotes} upvotes • 💬 ${product.comments} comments
        </div>
      </div>
    `;
  }).join('');
}

function buildHackerNewsSection(stories) {
  return stories.map(story => {
    return `
      <div class="item">
        <div class="item-title">
          <a href="${story.url}">${story.title}</a>
        </div>
        <div class="item-meta">
          ⬆️ ${story.points} points • 💬 ${story.comments} comments
        </div>
      </div>
    `;
  }).join('');
}

module.exports = { buildEmailTemplate };
