version = 0.1

[default.deploy.parameters]
stack_name = "openpaw-daily-digest"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "GmailClientId=\"\" RecipientEmail=\"\""
confirm_changeset = true
